version: "3"
services:
  pytest-console:
    build: .
    container_name: pytest-console
    env_file: .env
    command: sleep infinity
    volumes:
      - .:/app
      - py-venv-dummy:/app/.venv
    networks:
      - default

volumes:
  py-venv-dummy:
    driver: local
